# Datos para la configuración del Cliente, session para enviar y recibir mensajes en API
bot:
  # Api_id y #Api_hash obtienes en : https://my.telegram.org
  _api_id: 7746861
  _api_hash: "54b9e1de05058f6ab2eb122d5a74ac05"
  # El token del bot se obtiene en : @BotFather
  _bot_token: "7267421305:AAEjgLfKUj6MZn5jsDgE_tGoC6IYWMdvI2Y"

# Datos para la base de datos eso varia segun tu proveedor de db
database:
  host: "localhost"
  user: root
  pass: ""
  dbname: bot

bot_data:
  version: "1.6"
  last_update: "09/08/24"
  Database_Type: "MongoDB"
